@baseUrl = http://localhost:3000
//@token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTkyNTVhMC05MzFkLTQ2YjYtOTYzYy1iNjNhNDZmOGE5NDgiLCJlbWFpbCI6ImFybWFuZG9AZ21haWwuY29tIiwiaWF0IjoxNzU1Mjc5MDY3LCJleHAiOjE3NTUzNjU0Njd9.9x39DMr9WgAgeTIa2tnztSdHyhgflhyhNjp8DRPcbu8'
@token= {{authLogin.response.body.accessToken}}
###
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "armando@gmail.com",
  "password": "Aa123456#"
//  "Malware": "Script"
//  "teste":"123"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Teste Ribamar",
  "email": "teste@gmail.com",
  "password": "Aa123456#"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Armando Ribamar",
  "email": "armando@gmail.com"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "Aa123456#",
  "newPassword": "Aa123456#"
}

### Read one User
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}

###

### Delete one User
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{token}}

###
