@baseUrl = http://localhost:3000
//@token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTkyNTVhMC05MzFkLTQ2YjYtOTYzYy1iNjNhNDZmOGE5NDgiLCJlbWFpbCI6ImFybWFuZG9AZ21haWwuY29tIiwiaWF0IjoxNzU1Mjc5MDY3LCJleHAiOjE3NTUzNjU0Njd9.9x39DMr9WgAgeTIa2tnztSdHyhgflhyhNjp8DRPcbu8'
@token= {{authLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}/{{imagePath}}

@userNameForTesting = Armando
@userEmailForTesting = armando@gmail.com
@userPasswordForTesting = Aa123456#
@userNewPasswordForTesting = Aa123456#


###
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
//  "Malware": "Script"
//  "teste":"123"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Armando Ribamar",
  "email": "armando@gmail.com",
  "password": "Aa123456#"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Armando Ribamar",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "{{userPasswordForTesting}}",
  "newPassword": "{{userNewPasswordForTesting}}"
}

### Read one User
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}

###

### Delete one User
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{token}}

### Create Post
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Novo Titulo do Post",
  "content": "Conteudo do Post alongado",
  "excerpt": "Excerto do Post",
  "coverImageUrl": "{{imageUrl}}"
}

### Read one Post
# @name readOnePostPublic
GET {{baseUrl}}/post/{{postSlug}}

##### Read one Post
# @name readOnePostOwned
GET {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{token}}

### Update Post
# @name updatePostOwned
PATCH {{baseUrl}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "NOVO - Titulo do Post",
  "content": "NOVO - Conteudo do Post",
  "excerpt": "NOVO - Conteudo",
  "published": true
}

### Delete Post
# @name deletePostOwned
DELETE {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{token}}


### Read All post owned
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{token}}

### Read All post public
# @name readAllPostPublic
GET {{baseUrl}}/post

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ../dev/images/image.png
------BryenFormBoundary--

### Read Image
# @name readImage
GET {{imageUrl}}

###############################################################################